using System.Globalization;
using System.Text;
using Dmart.DataAdapters.Sql;
using Dmart.Models.Api;
using Dmart.Models.Enums;
using Dmart.QueryGrammar;
using Npgsql;
using Shouldly;
using Xunit;

namespace Dmart.Tests.Unit.Sql;

// Byte-for-byte snapshot of every SQL fragment csdmart emits from a pure
// (no-connection-required) builder, plus the bound parameters' types and values.
//
// This exists to make the PostgreSQL dialect's emitted SQL a *checked-in
// artifact* rather than something re-derived at review time. The SQLite backend
// work introduces an ISqlDialect seam between the query builders and the
// provider; the hard constraint on that work is that the PostgreSQL path keeps
// emitting the identical text. A snapshot test is the only way to prove that
// mechanically instead of by inspection over ~1600 lines of string building.
//
// The corpus deliberately covers the dialect-sensitive constructs the SQLite
// port has to replace — JSONB containment/`->`/`->>`/`jsonb_typeof`, `?|`,
// `unnest`, ILIKE/LIKE, `= ANY($n)`, timestamp casts — so that any accidental
// change to PostgreSQL emission surfaces here as a diff instead of in
// production.
//
// To regenerate after an INTENTIONAL emission change:
//     UPDATE_SQL_GOLDEN=1 dotnet test --filter SqlEmissionGoldenTests
// then read the diff carefully. A non-empty diff during the seam work means
// the seam changed behaviour and is a bug, not a golden to refresh.
public class SqlEmissionGoldenTests
{
    private static readonly string GoldenPath = Path.Combine(
        GetTestDirectory(), "sql-emission.golden.txt");

    [Fact]
    public void EmittedSql_MatchesGolden()
    {
        var actual = BuildCorpusReport();

        if (Environment.GetEnvironmentVariable("UPDATE_SQL_GOLDEN") == "1")
        {
            File.WriteAllText(GoldenPath, actual);
            return;
        }

        File.Exists(GoldenPath).ShouldBeTrue(
            $"Golden file missing at {GoldenPath}. Regenerate with UPDATE_SQL_GOLDEN=1.");

        var expected = File.ReadAllText(GoldenPath);

        // Report the first differing line rather than dumping two 700-line
        // blobs — a snapshot failure is only actionable if you can see WHERE.
        if (!string.Equals(expected, actual, StringComparison.Ordinal))
        {
            var e = expected.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
            var a = actual.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
            for (var i = 0; i < Math.Max(e.Length, a.Length); i++)
            {
                var el = i < e.Length ? e[i] : "<end of file>";
                var al = i < a.Length ? a[i] : "<end of file>";
                if (!string.Equals(el, al, StringComparison.Ordinal))
                {
                    throw new Xunit.Sdk.XunitException(
                        $"Emitted SQL diverged from the golden snapshot at line {i + 1}.\n"
                        + $"  golden: {el}\n"
                        + $"  actual: {al}\n"
                        + "If this change is intentional, regenerate with UPDATE_SQL_GOLDEN=1 "
                        + "and review the resulting diff. During the SQLite seam work a diff "
                        + "here means the PostgreSQL path changed — that is a bug.");
                }
            }
        }
    }

    // ── Corpus ────────────────────────────────────────────────────────────

    private static string BuildCorpusReport()
    {
        var sb = new StringBuilder();
        sb.Append("# csdmart emitted-SQL snapshot (PostgreSQL dialect)\n");
        sb.Append("# Generated by SqlEmissionGoldenTests. Do not hand-edit.\n");

        foreach (var (name, sql, args) in WhereClauseCases()) Emit(sb, "where", name, sql, args);
        foreach (var (name, sql, args) in AclCases()) Emit(sb, "acl", name, sql, args);
        foreach (var (name, sql, args) in SemiJoinCases()) Emit(sb, "semijoin", name, sql, args);
        foreach (var (name, sql, args) in OrderPagingCases()) Emit(sb, "orderpaging", name, sql, args);
        foreach (var (name, sql, args) in SearchCases()) Emit(sb, "search", name, sql, args);
        foreach (var (name, sql, args) in AggregationCases()) Emit(sb, "aggregation", name, sql, args);
        foreach (var (name, expr) in JoinKeyCases()) sb.Append($"\n## joinkey: {name}\nEXPR: {expr}\n");

        return sb.ToString();
    }

    private static IEnumerable<(string, string, List<NpgsqlParameter>)> WhereClauseCases()
    {
        foreach (var (name, q, table) in new (string, Query, string?)[]
        {
            ("base-root", Q("myspace", "/"), "entries"),
            ("hierarchical-subpath", Q("myspace", "/posts"), "entries"),
            ("exact-subpath", Q("myspace", "/posts") with { ExactSubpath = true }, "entries"),
            ("exact-subpath-root", Q("myspace", "/") with { ExactSubpath = true }, "entries"),
            ("filter-types", Q("s", "/") with
            {
                FilterTypes = new() { ResourceType.Content, ResourceType.Folder },
            }, "entries"),
            ("filter-shortnames", Q("s", "/") with
            {
                FilterShortnames = new() { "alpha", "beta" },
            }, "entries"),
            ("filter-schema-names", Q("s", "/") with
            {
                FilterSchemaNames = new() { "note", "meta", "article" },
            }, "entries"),
            ("filter-schema-names-meta-only", Q("s", "/") with
            {
                FilterSchemaNames = new() { "meta" },
            }, "entries"),
            ("filter-tags", Q("s", "/") with { FilterTags = new() { "red", "blue" } }, "entries"),
            ("date-range", Q("s", "/") with
            {
                FromDate = new DateTime(2026, 1, 2, 3, 4, 5, DateTimeKind.Unspecified),
                ToDate = new DateTime(2026, 6, 7, 8, 9, 10, DateTimeKind.Unspecified),
            }, "entries"),
            ("everything-at-once", Q("s", "/deep/path") with
            {
                FilterTypes = new() { ResourceType.Ticket },
                FilterShortnames = new() { "x" },
                FilterSchemaNames = new() { "sch" },
                FilterTags = new() { "t1" },
                Search = "@payload.body.status:open",
                FromDate = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Unspecified),
            }, "entries"),
            ("table-users", Q("management", "/users"), "users"),
        })
        {
            var args = new List<NpgsqlParameter>();
            yield return (name, QueryHelper.BuildWhereClause(q, args, table), args);
        }

        // Nested reuse: args already populated, so $N must continue, not restart.
        {
            var args = new List<NpgsqlParameter> { new() { Value = "pre1" }, new() { Value = "pre2" } };
            yield return ("nested-continues-positional",
                QueryHelper.BuildWhereClause(Q("rightspace", "/"), args, "entries"), args);
        }
    }

    private static IEnumerable<(string, string, List<NpgsqlParameter>)> AclCases()
    {
        foreach (var (name, user, table, policies) in new (string, string?, string, List<string>?)[]
        {
            ("no-user", null, "entries", null),
            ("user-no-policies", "alice", "entries", null),
            ("user-with-policies", "alice", "entries", new() { "myspace:/posts:*", "other:/x:content" }),
            // Policy shapes BuildUserQueryPolicies actually emits: enumerable,
            // so they reach the indexable `&&` test.
            ("user-with-expandable-policies", "alice", "entries",
                new() { "myspace:posts:content:true:*", "myspace:posts:content:*" }),
            // Mixed: one enumerable, one that keeps LIKE.
            ("user-with-mixed-policies", "alice", "entries",
                new() { "myspace:posts:content:true:alice", "*:legacy:content:true:bob" }),
            ("policy-metachars", "alice", "entries", new() { @"sp:/a_b:100%\x", "sp:/*" }),
            ("skipped-attachments", "alice", "attachments", new() { "a:*" }),
            ("skipped-histories", "alice", "histories", new() { "a:*" }),
            ("table-users", "alice", "users", new() { "management:/users:*" }),
        })
        {
            var sql = new StringBuilder();
            var args = new List<NpgsqlParameter>();
            QueryHelper.AppendAclFilter(sql, args, user, table, policies);
            yield return (name, sql.ToString(), args);
        }
    }

    private static IEnumerable<(string, string, List<NpgsqlParameter>)> SemiJoinCases()
    {
        var sql = new StringBuilder();
        var args = new List<NpgsqlParameter>();
        QueryHelper.AppendInnerSemiJoins(sql, args, new[]
        {
            new InnerSemiJoinSpec
            {
                RightQuery = Q("rspace", "/right"),
                Actor = "alice",
                RightQueryPolicies = new() { "rspace:/right:*" },
                Correlations = new() { ("entries.shortname", "r.subpath") },
            },
        });
        yield return ("single-inner", sql.ToString(), args);

        var sql2 = new StringBuilder();
        var args2 = new List<NpgsqlParameter>();
        QueryHelper.AppendInnerSemiJoins(sql2, args2, new[]
        {
            new InnerSemiJoinSpec
            {
                RightQuery = Q("a", "/one"),
                Actor = "bob",
                RightQueryPolicies = null,
                Correlations = new() { ("entries.uuid", "r.uuid") },
            },
            new InnerSemiJoinSpec
            {
                RightQuery = Q("b", "/two") with { Search = "@is_active:true" },
                Actor = "bob",
                RightQueryPolicies = new() { "b:*" },
                Correlations = new() { ("entries.shortname", "r.shortname"), ("entries.subpath", "r.subpath") },
            },
        });
        yield return ("two-inner-with-search", sql2.ToString(), args2);
    }

    private static IEnumerable<(string, string, List<NpgsqlParameter>)> OrderPagingCases()
    {
        foreach (var (name, q, table) in new (string, Query, string?)[]
        {
            ("default", Q("s", "/"), "entries"),
            ("random", Q("s", "/") with { Type = QueryType.Random }, "entries"),
            ("sort-ascending", Q("s", "/") with { SortBy = "shortname", SortType = SortType.Ascending }, "entries"),
            ("sort-descending", Q("s", "/") with { SortBy = "created_at", SortType = SortType.Descending }, "entries"),
            ("sort-multi", Q("s", "/") with { SortBy = "shortname,updated_at", SortType = SortType.Ascending }, "entries"),
            ("sort-json-path", Q("s", "/") with { SortBy = "payload.body.priority", SortType = SortType.Descending }, "entries"),
            ("sort-unknown-column-falls-back", Q("s", "/") with { SortBy = "definitely_not_a_column" }, "entries"),
            ("limit-offset", Q("s", "/") with { Limit = 250, Offset = 500 }, "entries"),
            ("limit-clamped", Q("s", "/") with { Limit = 0, Offset = -5 }, "entries"),
        })
        {
            var sql = new StringBuilder();
            var args = new List<NpgsqlParameter>();
            QueryHelper.AppendOrderAndPaging(sql, q, args, table);
            yield return (name, sql.ToString(), args);
        }
    }

    // The search grammar is where nearly all of the JSONB dialect surface lives,
    // so it gets the widest corpus — one case per emission branch.
    private static readonly (string Name, string Expr)[] SearchExpressions =
    {
        ("plain-text-term", "hello"),
        ("two-text-terms", "hello world"),
        ("meta-equality", "@shortname:alpha"),
        ("meta-alternation", "@shortname:alpha|beta"),
        ("meta-negated", "-@shortname:alpha"),
        ("payload-containment", "@payload.body.status:open"),
        ("payload-containment-nested", "@payload.body.deep.nested.key:value"),
        ("payload-numeric", "@payload.body.count:42"),
        ("payload-comparison-gt", "@payload.body.count:>10"),
        ("payload-comparison-gte", "@payload.body.count:>=10"),
        ("payload-comparison-lt", "@payload.body.count:<10"),
        ("payload-comparison-lte", "@payload.body.count:<=10"),
        ("payload-comparison-neq", "@payload.body.count:!10"),
        ("payload-negated", "-@payload.body.status:open"),
        ("payload-null-check", "@payload.body.status:null"),
        ("payload-null-check-negated", "-@payload.body.status:null"),
        ("payload-existence", "@payload.body.status:*"),
        ("payload-wildcard-contains", "@payload.body.title:*foo*"),
        ("payload-wildcard-prefix", "@payload.body.title:foo*"),
        ("payload-wildcard-suffix", "@payload.body.title:*foo"),
        ("payload-wildcard-negated", "-@payload.body.title:*foo*"),
        ("payload-wildcard-metachars", @"@payload.body.title:*a%b_c\d*"),
        // Array iteration (BuildPayloadArraySql). The two engines need
        // different set-returning functions and element dereferencing here, so
        // these pin the PostgreSQL side of that.
        ("payload-array-scalar", "@payload.tags[]:red"),
        ("payload-array-subpath", "@payload.items[].price:100"),
        ("payload-array-subpath-nested", "@payload.items[].meta.sku:abc"),
        ("payload-array-numeric-gt", "@payload.items[].price:>5"),
        ("payload-array-numeric-range", "@payload.items[].price:[5 10]"),
        ("payload-array-negated", "-@payload.items[].price:100"),
        ("payload-array-scalar-negated", "-@payload.tags[]:red"),
        ("payload-boolean-true", "@payload.body.enabled:true"),
        ("payload-boolean-false", "@payload.body.enabled:false"),
        ("jsonb-array-tags", "@tags:red"),
        ("jsonb-array-tags-negated", "-@tags:red"),
        ("jsonb-array-roles", "@roles:admin"),
        ("jsonb-array-groups", "@groups:staff"),
        ("text-array-query-policies", "@query_policies:space:/a:content"),
        ("text-array-wildcard", "@query_policies:space*"),
        ("boolean-column-is-active", "@is_active:true"),
        ("boolean-column-is-open-negated", "-@is_open:false"),
        ("timestamp-range", "@created_at:[2026-01-01 2026-12-31]"),
        ("timestamp-range-numeric", "@created_at:[1700000000000 1800000000000]"),
        ("timestamp-range-reversed", "@created_at:[2026-12-31 2026-01-01]"),
        ("timestamp-comparison", "@updated_at:>2026-01-01"),
        ("user-meta-email", "@email:a@example.com"),
        ("user-meta-msisdn", "@msisdn:+9647000000"),
        ("or-group", "@shortname:a or @shortname:b"),
        ("and-implicit", "@shortname:a @is_active:true"),
        ("parens-group", "(@shortname:a or @shortname:b) @is_active:true"),
        ("nested-parens", "((@tags:x or @tags:y) @is_active:true) or @shortname:z"),
        ("unbalanced-paren-noise", "@shortname:a) or @shortname:b"),
        ("quoted-value", "@payload.body.title:\"hello world\""),
        ("over-length-fails-closed", null!),  // built below
        ("empty", ""),
    };

    private static IEnumerable<(string, string, List<NpgsqlParameter>)> SearchCases()
    {
        foreach (var (name, expr) in SearchExpressions)
        {
            var effective = name == "over-length-fails-closed"
                ? new string('a', SearchExpressionParser.MaxExpressionLength + 1)
                : expr;

            // Both placeholder styles: the server uses Positional, the SDK Named.
            foreach (var style in new[] { PlaceholderStyle.Positional, PlaceholderStyle.Named })
            {
                var parsed = SearchExpressionParser.Parse(effective, 0, style, "entries");
                yield return ($"{name}[{style}]",
                    string.Join(" AND ", parsed.Clauses),
                    Materialize(parsed.Parameters));
            }
        }

        // targetTable gates the user-meta join — same expression, two emissions.
        foreach (var table in new[] { "entries", "users" })
        {
            var parsed = SearchExpressionParser.Parse("@email:a@b.com", 0, PlaceholderStyle.Positional, table);
            yield return ($"user-meta-target-{table}",
                string.Join(" AND ", parsed.Clauses), Materialize(parsed.Parameters));
        }

        // Non-zero starting index: numbering must continue from the caller's.
        {
            var parsed = SearchExpressionParser.Parse("@shortname:a", 7, PlaceholderStyle.Positional, "entries");
            yield return ("starting-index-7",
                string.Join(" AND ", parsed.Clauses), Materialize(parsed.Parameters));
        }
    }

    // One case per reducer, because the reducer vocabulary is exactly what the
    // SQLite dialect cannot fully implement (§2.8 of the audit: percentile_cont,
    // stddev and ordered ARRAY_AGG have no equivalent). Snapshotting each keeps
    // the PostgreSQL emission pinned while that divergence gets built.
    private static IEnumerable<(string, string, List<NpgsqlParameter>)> AggregationCases()
    {
        static RedisReducer R(string name, string? alias, params string[] args)
            => new() { ReducerName = name, Alias = alias, Args = args.ToList() };

        foreach (var (name, agg, user, policies) in new (string, RedisAggregate, string?, List<string>?)[]
        {
            ("count-no-group", new() { Reducers = { R("count", null) } }, null, null),
            ("count-field", new() { Reducers = { R("count", "n", "@payload.body.x") } }, null, null),
            ("count-distinct", new() { Reducers = { R("count_distinct", null, "@shortname") } }, null, null),
            ("sum", new() { Reducers = { R("sum", "total", "@payload.body.amount") } }, null, null),
            ("avg", new() { Reducers = { R("avg", null, "@payload.body.amount") } }, null, null),
            ("min-max", new()
            {
                Reducers = { R("min", "lo", "@payload.body.amount"), R("max", "hi", "@payload.body.amount") },
            }, null, null),
            ("stddev", new() { Reducers = { R("stddev", null, "@payload.body.amount") } }, null, null),
            ("group-concat", new() { Reducers = { R("group_concat", null, "@shortname") } }, null, null),
            ("quantile-default", new() { Reducers = { R("quantile", null, "@payload.body.amount") } }, null, null),
            ("quantile-explicit", new() { Reducers = { R("quantile", "p90", "@payload.body.amount", "0.9") } }, null, null),
            ("quantile-clamped", new() { Reducers = { R("quantile", null, "@payload.body.amount", "5") } }, null, null),
            ("first-value", new() { Reducers = { R("first_value", null, "@shortname") } }, null, null),
            ("random-sample", new() { Reducers = { R("random_sample", null, "@shortname") } }, null, null),
            ("group-by-single", new()
            {
                GroupBy = { "@resource_type" }, Reducers = { R("count", null) },
            }, null, null),
            ("group-by-json-path", new()
            {
                GroupBy = { "@payload.body.category" }, Reducers = { R("count", null) },
            }, null, null),
            ("group-by-multi", new()
            {
                GroupBy = { "@resource_type", "@payload.body.category" }, Reducers = { R("count", "n") },
            }, null, null),
            ("with-acl", new()
            {
                GroupBy = { "@resource_type" }, Reducers = { R("count", null) },
            }, "alice", new() { "s:/*" }),
            ("unknown-reducer-dropped", new() { Reducers = { R("not_a_reducer", null, "@x") } }, null, null),
        })
        {
            var q = Q("s", "/") with { Type = QueryType.Aggregation, AggregationData = agg };
            var built = QueryHelper.BuildAggregationSql("entries", q, user, policies);
            yield return built is null
                ? (name, "<no selectable columns>", new List<NpgsqlParameter>())
                : (name, built.Value.Sql, built.Value.Args);
        }

        // No aggregation block at all → null, not an empty statement.
        {
            var built = QueryHelper.BuildAggregationSql("entries", Q("s", "/"));
            yield return ("no-aggregation-block",
                built is null ? "<null>" : built.Value.Sql, new List<NpgsqlParameter>());
        }
    }

    // Snapshot the NpgsqlParameter the server will actually bind, not the
    // grammar's neutral descriptor. The descriptor is an implementation detail
    // of the seam; what must not change is the concrete parameter PostgreSQL
    // receives — in particular whether NpgsqlDbType was set at all, since an
    // untagged parameter resolves as `unknown` server-side and a tagged one
    // does not.
    private static List<NpgsqlParameter> Materialize(IReadOnlyList<SqlParam> pars)
        => pars.Select(PostgresDialect.CreateParameter).ToList();

    private static IEnumerable<(string, string)> JoinKeyCases()
    {
        foreach (var (name, path) in new[]
        {
            ("shortname", "shortname"),
            ("subpath", "subpath"),
            ("uuid", "uuid"),
            ("resource-type", "resource_type"),
            ("payload-path", "payload.body.ref"),
            ("rejected-unknown", "not_a_join_key"),
            ("rejected-injection", "shortname; DROP TABLE entries"),
        })
        {
            // Qualifier carries its own trailing dot — QueryService passes
            // "entries." and "r." (QueryService.cs:1429-1430).
            yield return (name,
                QueryHelper.TryJoinKeyToSql(path, "r.", out var expr) ? expr : "<rejected>");
        }
    }

    // ── Rendering ─────────────────────────────────────────────────────────

    private static void Emit(StringBuilder sb, string kind, string name, string sql, List<NpgsqlParameter> args)
    {
        sb.Append($"\n## {kind}: {name}\n");
        sb.Append("SQL: ").Append(sql.Length == 0 ? "<empty>" : sql).Append('\n');
        for (var i = 0; i < args.Count; i++)
            sb.Append($"  P{i + 1}: {DescribeParam(args[i])}\n");
    }

    // Renders name + declared NpgsqlDbType + value. The declared type matters as
    // much as the text: the seam replaces explicit NpgsqlDbType tagging with a
    // provider-neutral kind, and a silently-dropped Jsonb/Boolean tag would
    // change how PostgreSQL casts the parameter without changing the SQL string.
    private static string DescribeParam(NpgsqlParameter p)
    {
        var name = string.IsNullOrEmpty(p.ParameterName) ? "<positional>" : p.ParameterName;
        return $"name={name} type={DescribeDeclaredType(p)} value={RenderValue(p.Value)}";
    }

    // Reports the type tag the code EXPLICITLY attached, or <inferred> when it
    // let Npgsql decide.
    //
    // Reading p.NpgsqlDbType directly is not stable enough to snapshot.
    // Npgsql infers it lazily from Value, and the inferred answer depends on
    // whether the global type mapper has been initialized — which happens the
    // first time any connection opens. So the same parameter reports Unknown in
    // a unit-only run and Text in a run that also opened a database, and the
    // snapshot fails depending on which tests ran alongside it.
    //
    // Comparing against a same-valued untyped probe removes that dependence:
    // both are inferred under identical global state, so a difference means the
    // code set the type deliberately. That is exactly the property worth
    // pinning — a dropped Jsonb tag changes how PostgreSQL casts the value
    // without changing the SQL text. Tags that merely restate what inference
    // would produce (Boolean on a bool, Array|Text on a string[]) report as
    // <inferred>, which is correct: they are behaviourally identical.
    private static string DescribeDeclaredType(NpgsqlParameter p)
    {
        NpgsqlTypes.NpgsqlDbType actual;
        try { actual = p.NpgsqlDbType; }
        catch (InvalidCastException) { return "<uninferrable>"; }
        catch (NotSupportedException) { return "<unsupported>"; }
        catch (ArgumentException) { return "<uninferrable>"; }

        // A tag that merely restates the CLR value's natural PostgreSQL type
        // carries no information and, worse, is reported inconsistently:
        // uninitialized, Npgsql answers Unknown; once a connection has
        // initialized the global type mapper, it answers the natural type. The
        // mapping below is keyed only on the CLR type, so the snapshot depends
        // on nothing outside this method.
        //
        // What survives normalization is the case that actually matters: a tag
        // that OVERRIDES inference, such as Jsonb on a string. Dropping one of
        // those changes how PostgreSQL casts the value while leaving the SQL
        // text untouched, which is precisely what this snapshot exists to catch.
        return actual == NpgsqlTypes.NpgsqlDbType.Unknown || actual == NaturalType(p.Value)
            ? "<inferred>"
            : DescribeDbType(actual);
    }

    private static NpgsqlTypes.NpgsqlDbType NaturalType(object? value) => value switch
    {
        string => NpgsqlTypes.NpgsqlDbType.Text,
        bool => NpgsqlTypes.NpgsqlDbType.Boolean,
        string[] => NpgsqlTypes.NpgsqlDbType.Array | NpgsqlTypes.NpgsqlDbType.Text,
        DateTime => NpgsqlTypes.NpgsqlDbType.Timestamp,
        double => NpgsqlTypes.NpgsqlDbType.Double,
        int => NpgsqlTypes.NpgsqlDbType.Integer,
        long => NpgsqlTypes.NpgsqlDbType.Bigint,
        Guid => NpgsqlTypes.NpgsqlDbType.Uuid,
        byte[] => NpgsqlTypes.NpgsqlDbType.Bytea,
        _ => NpgsqlTypes.NpgsqlDbType.Unknown,
    };

    // NpgsqlDbType.Array is a flag (int.MinValue) OR'd onto an element type, so
    // `Array | Text` has no enum name and renders as a bare -2147483629. Decode
    // it so the snapshot stays readable in a review diff.
    private static string DescribeDbType(NpgsqlTypes.NpgsqlDbType dbType)
    {
        const NpgsqlTypes.NpgsqlDbType arrayFlag = NpgsqlTypes.NpgsqlDbType.Array;
        if ((dbType & arrayFlag) == arrayFlag && dbType != arrayFlag)
            return "Array|" + (dbType & ~arrayFlag);
        return dbType.ToString();
    }

    private static string RenderValue(object? value) => value switch
    {
        null => "<null>",
        DBNull => "<dbnull>",
        string s => $"\"{s}\"",
        bool b => b ? "true" : "false",
        double d => d.ToString("R", CultureInfo.InvariantCulture),
        DateTime dt => dt.ToString("yyyy-MM-dd HH:mm:ss.fffffff", CultureInfo.InvariantCulture)
                       + $" (Kind={dt.Kind})",
        Guid g => g.ToString("D"),
        string[] arr => "[" + string.Join(", ", arr.Select(x => $"\"{x}\"")) + "]",
        int i => i.ToString(CultureInfo.InvariantCulture),
        _ => $"{value.GetType().Name}:{Convert.ToString(value, CultureInfo.InvariantCulture)}",
    };

    private static Query Q(string space, string subpath) => new()
    {
        Type = QueryType.Subpath, SpaceName = space, Subpath = subpath,
    };

    // The golden lives beside the test source, not in the build output, so it
    // is reviewable in a diff. Walk up from the assembly location to find it.
    private static string GetTestDirectory([System.Runtime.CompilerServices.CallerFilePath] string path = "")
        => Path.GetDirectoryName(path)!;
}
