# dmart deployment inventory
# Edit with your server hostnames/IPs

[fedora]
i7.imx.sh
# fedora1.example.com
# fedora2.example.com

[el9]
hr-prod
hr-dev
evd-dev
# rhel1.example.com
# rhel2.example.com

[all:vars]
# ansible_user=root
dmart_rpm_dir=../../dist/out
